# Copyright AstraZeneca 2026
import numpy as np
import torch
from scipy.spatial import KDTree

from linguine.utils.bounding_boxes import BBox3D


def find_closest_point(
    positives: tuple[np.ndarray, ...] | tuple[torch.Tensor],
    target: np.ndarray | tuple[int],
    bf_threshold: int = 256,
) -> tuple[int, ...]:
    """
    Find the closest point in parsed array to target with KD-Tree.

    Args:
        positives: list of coors to search from. Generated by np.where() function.
        target: Coordiantes of the target point.
        bf_threshold: Threshold of number of samples to switch to brute-force method.

    Returns:
        tuple[int, ...]: Nearest point from "positives" to target.
    """
    if not len(positives) or not len(positives[0]):
        raise ValueError("Search array is empty.")

    # Convert torch input if necessary.
    positive_numpy: list[np.ndarray] = positives
    if isinstance(positives[0], torch.Tensor):
        positive_numpy = [x.cpu().numpy().astype(int) for x in positives]
    array_t: np.ndarray = np.array(positive_numpy).transpose()
    # Search for the nearest neighbor.
    tree: KDTree = KDTree(array_t, leafsize=bf_threshold)
    _, index = tree.query(target)
    return tuple(array_t[index])


def location_is_valid(loc: tuple[int, int, int], arr: np.ndarray | torch.Tensor) -> bool:
    """Checks if the input location is a valid location in the given array.

    Args:
        loc: a coordinate location in the array space in the form (x,y,z).
        arr: the array that the coordinate belongs to.

    Returns:
        bool to specify if location is valid.
    """
    if any(x < 0 for x in loc):
        return False
    if any(x >= b for x, b in zip(loc, arr.shape)):
        return False
    return True


def filter_invalid_prompts(
    img: torch.Tensor,
    fg_clicks: list[tuple[int, int, int]],
    bg_clicks: list[tuple[int, int, int]],
    bboxes: list[BBox3D],
) -> tuple[list[tuple[int, int, int]], list[tuple[int, int, int]], list[BBox3D]]:
    """Filters out any prompts that are incompatible with the input image.

    Args:
        img: 3D Image tensor
        fg_clicks: a list of foreground guidance clicks.
        bg_clicks: a list of background guidance clicks.
        bboxes: a list of bounding boxes.

    Returns:
        A tuple containing the filtered foreground clicks, background clicks, and bounding boxes.
    """

    # Filter bboxes - remove bboxes with any coordinate outside image boundaries
    filtered_bboxes = []
    for bbox in bboxes:
        # Check if all bbox coordinates are within image bounds
        if location_is_valid((bbox.x_min, bbox.y_min, bbox.z_min), img) and location_is_valid(
            (bbox.x_max, bbox.y_max, bbox.z_max), img
        ):
            filtered_bboxes.append(bbox)

    return (
        [i for i in fg_clicks if location_is_valid(i, img)],
        [i for i in bg_clicks if location_is_valid(i, img)],
        filtered_bboxes,
    )
